### ISSUE TITLE
wifi 5ghz

### ISSUE THREAD

**Issue by wellingtonfernandesbarbosa** [linuxmint/warpinator#100]
Is there any limitations to work in wifi 5ghz. I tried to connect my Galaxy Tab 8(2019) trough the router of 5ghz it's don't work. Them I connect the tablet trough a router working on 2.4ghz in the same network and it's work.
I know the WiFi 2.4ghz have limitations in transfer of files, and it's the reason to make work in wifi 5ghz.
Sorry for my English. 
I hope that someone is able to help me.

**Comment by mtwebster** [comment]
There should be no issues that I know of - this is really at a much lower level than we're dealing with in the app - there's really no distinction as far as it knows.

Are they both from the same router/ap? Do they have distinct ssids? Are they configured the same in the firmware? Are you too far away? 5ghz has lower range and can be affected by obstacles more.
