### ISSUE TITLE
Run without a GUI?

### ISSUE THREAD

**Issue by coreyog** [linuxmint/warpinator#106]
I often run my linux mint machine without a GUI by executing the following command:

    sudo systemctl set-default multi-user.target

I updated to Linux Mint yesterday and got warpinator all set up while the GUI was active and then ran the above to switch back. I noticed that warpinator does not run while my machine is configured this way, when starting warpinator from the command line, I get the following output:

    Unable to init server: Could not connect: Connection refused
    Unable to init server: Could not connect: Connection refused

Is it possible to run warpinator without a display?

**Comment by mtwebster** [comment]
I don't think so - the gui toolkit (gtk) is counting on there being a display server.

Maybe you could use a dummy display server? There's lots of info out there for 'headless' setups that may work for you. If you don't *always* run it this way, I imagine you may need take additional steps.

If you can come up with some dummy server, you can specify `DISPLAY=:0 warpinator` for example, at runtime, if necessary.

**Comment by adigourdi** [comment]
This would be interesting, and useful to copy files into a local server

Maybe extract the logic into a lib ?

**Comment by mtwebster** [comment]
This is really outside the scope of what we're after here - a simple gui program folks can use to transfer files between computers.

**Comment by coreyog** [comment]
You don't support running without a GUI, you don't support non-linux builds... sounds like Warpinator isn't what I'm after.

**Comment by adigourdi** [comment]
This same simple gui program can use the lib with no impact on end users, and open the logic for more integrators in other OSs to include this feature

Warpinator is great, fast, and secure, other users would use it, and mint users will find a feature in their OS available instead of mint-to-mint only
