### ISSUE TITLE
Warpinator doesn't start emitting "can only concatenate str (not int) to str"

### ISSUE THREAD

**Issue by yesint** [linuxmint/warpinator#107]
On my Linux mint 20.2 laptop warpinator stopped working. If started from command line the following is printed:

```
$ warpinator
can only concatenate str (not "int") to str
```
Reinstalling the package doesn't help.
I can't google anything similar to this problem. Any suggestions?

**Comment by mtwebster** [comment]
Have you installed any python3 modules from other than the system package manager? Or a newer python3 version than what's included with Mint?

**Comment by yesint** [comment]
> Did you upgrade from 20.1 to 20.2? That's another scenario I can think of that would cause this - there was only a single port in the previous version. When the additional port was added during the upgrade, it may have ended up the same as the existing one. Regardless, this shouldn't have caused a crash - I'll leave this open until I get a chance to fix it.
> 
> Thanks

The problem appeared in 20.1 before the upgrade to 20.2. The upgrade itself doesn't fix it. However, I noticed that in 20.1 warpinator was pulled from backports repository (not sure if it explains anything).

**Comment by mtwebster** [comment]
Ah you're right, we backported the new version to 20.1, 20, this is possibly what happened, then.

**Comment by janos-r** [comment]
I just used these 2 commands to fix this on my mom's pc. I was suddenly wondering why her warpinator was not starting while visiting over the holidays.
Thank you very much for this thread! <3
