### ISSUE TITLE
Cursor in window "About Warpinator"

### ISSUE THREAD

**Issue by andrzej16913** [linuxmint/warpinator#117]
In pop-up window "About Warpinator" in version 1.2.9 there is a visible cursor. It is located at the beginning of first line. It can be moved on the text of the window by clicking in text or using side arrows. If you click up or down arrow whole line of text becomes highlighted. Even after highlighting some text cursor is still visible. It can be seen on attached pictures
![wrong_cursor1](https://user-images.githubusercontent.com/40276810/150431433-392f147c-0963-482a-a48c-a1d1ffddbc27.png)
![wrong_cursor2](https://user-images.githubusercontent.com/40276810/150431457-1a70db8a-5cfb-4aed-99d6-0c63ae841ef0.png)
.

**Comment by mtwebster** [comment]
I think maybe it has something to do with the fact that links can be embedded in the text on About windows, so they give an entry cursor to make it easier to select text.  When filing bug reports, the user is often asked to copy the version info as well.

Either way, it's not something we can control in Warpinator.
