### ISSUE TITLE
One machine is not able to connect to another even though both of them are recognized

### ISSUE THREAD

**Issue by FireRacing** [linuxmint/warpinator#124]
One of my computers is running xubuntu 21.10 and the other is running linuxmint 20.2 . I installed the application through flathub on my computer running xubuntu. I trired sending a file whose size was 6.6 GB but cancelled it since it was showing 24 hours as the estimated transfer time. I try to send the file again and it stops in the middle and shows me the offline indicator. I restart the application and this time it is showing that the other host is offline. On the other host it is showing that it is unable to connect to the other host even though the host is recognised on the other machine.
Here is the avahi log of the first machine:
+   wlo1 IPv4 TARUN-HP-PROBOOK-440-G4-7CBFADBFE0027CA5F9A2  _warpinator._tcp     local
+   wlo1 IPv4 TARUN-HP-LAPTOP-15-DY2XXX-81D2254AE67FD7thp
avahi log on the other computer:
![20220401_143005](https://user-images.githubusercontent.com/33418792/161231628-b4349061-57ff-47b4-9c06-0dee9ff351f9.jpg)
BFF1D3 _warpinator._tcp     local
Firewall is disabled on both computers

**Comment by mtwebster** [comment]
Those are some strange symptoms.  Do either of the computers have more than one network interface? If so, make sure to specify which cart in preferences, and not automatic.

We've added a section on troubleshooting in the README:
https://github.com/linuxmint/warpinator#troubleshooting-tips

If you have no luck, feel free to attach logs for each machine during a connection attempt (how is explained at the end of the readme)

**Comment by FireRacing** [comment]
It is able to send and receive files now.
