### ISSUE TITLE
Freeze on Ubuntu 22.04 using python3-grpcio 1.30.2-3build6

### ISSUE THREAD

**Issue by mtwebster** [linuxmint/warpinator#127]
Using latest pip version works fine.

Possible ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/grpc/+bug/1971114

**Comment by nafanz** [comment]
As far as I understand I have the same problem, I found several discussions on this topic. Some of them are linked here. But I still don't understand how to solve this problem.

```
OS: Ubuntu 22.04.1 LTS x86_64 
Kernel: 5.15.0-53-generic 
Uptime: 2 hours, 24 mins 
Packages: 2118 (dpkg), 31 (snap) 
Shell: bash 5.1.16 
Resolution: 1920x1200 
DE: GNOME 42.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal ntel Celeron G530 (2) @ 2.400GHz 
GPU: AMD ATI Radeon HD 7750/8740 / R7 250E 
Memory: 2235MiB / 7933MiB
```

warpinator 1.4.1
```
warpinator --debug
2022-11-29 21:20:32,327::warpinator: Initializing Warpinator
2022-11-29 21:20:32,328::warpinator::DEBUG: UI: Creating window and status icon -- warpinator.py (line 1032)
2022-11-29 21:20:32,329::warpinator::DEBUG: Starting network monitor -- networkmonitor.py (line 34)

(warpinator:20955): Gtk-CRITICAL **: 21:20:32.504: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
2022-11-29 21:20:32,584::warpinator::DEBUG: Automatic interface selection: enp3s0 -- networkmonitor.py (line 187)
2022-11-29 21:20:32,584::warpinator::DEBUG: Network client initialized -- warpinator.py (line 1073)
2022-11-29 21:20:32,585::warpinator::DEBUG: New server requested for 'enp3s0' (192.168.88.246) -- warpinator.py (line 1101)
2022-11-29 21:20:32,586::warpinator::DEBUG: Auth: Creating server credentials -- auth.py (line 216)
2022-11-29 21:20:33,190::warpinator::DEBUG: Server: starting server on 192.168.88.246 (enp3s0) -- server.py (line 277)
2022-11-29 21:20:33,191::warpinator: Using api version 2
2022-11-29 21:20:33,191::warpinator: Our uuid: NAFANZ-DESKTOP-5A8806F41F6F36946A5A
2022-11-29 21:20:33,191::warpinator::DEBUG: Starting v1 registration server (192.168.88.246) with port 42000 -- remote_registration.py (line 62)
2022-11-29 21:20:33,191::warpinator::DEBUG: Starting v2 registration server (192.168.88.246) with auth port 42001 -- remote_registration.py (line 64)
```
As I understand it, I have two versions of grpcio installed on my system, via apt and pip. Both 1.30.2. Do I need to remove one?

**Comment by mtwebster** [comment]
Did you build this yourself? The meson build option `bundle-grpc-with-py310` needs to be set to true (it should be if you built it with dpkg-buildpackage)

This bundles grpc 1.44 with the warpinator package.

The other option is to use these packages: https://github.com/linuxmint/warpinator/releases/tag/master.mint21

Or, remove python3-grpcio package and downgrade grpcio to 1.44.0 using pip

**Comment by nafanz** [comment]
Yes, I collected according to the instructions.

`git checkout 1.2.3 \ 1.4.1` - Tried both versions
`dpkg-buildpackage --no-sign`

One of these days I will check your advice, but apparently I will have to read `meson`. I have not collected packages before.

On another PC, version 1.4.1 was installed without problems.
```
python3-grpc-tools 1.14.1-2
python3-grpcio 1.30.2-3
```
```
OS: Ubuntu 21.10 x86_64 
Host: Z87M-D3H 
Kernel: 5.13.0-52-generic 
Uptime: 3 hours, 4 mins 
Packages: 2621 (dpkg), 30 (snap) 
Shell: bash 5.1.8 
Resolution: 1920x1200 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-4430 (4) @ 3.200GHz 
GPU: Intel HD Graphics 
Memory: 6005MiB / 11859MiB
```

**Comment by nafanz** [comment]
I deleted
`sudo apt remove python3-grpcio`
This also resulted in automatic deletion
`python3-grpc-tools warpinator`
Installed
`sudo pip3 install grpcio=1.44.0`
Tried to collect warpinator 1.4.2
`dpkg-buildpackage --no-sign`
Lack of dependency
`Unmet build dependencies: python3-grpc-tools (>= 1.14.0)`
Installed the latest version
`sudo pip3 install grpcio-tools`
But when assembling warpinator, he still says about the absence. I downvoted but that didn't help either
`sudo pip3 install grpcio-tools==1.14.0`
As a result, I installed
`sudo apt install python3-grpc-tools`
He installed them both
```
Пол:1 http://ru.archive.ubuntu.com/ubuntu jammy/universe amd64 python3-grpcio amd64 1.30.2-3build6 [1 281 kB]
Пол:2 http://ru.archive.ubuntu.com/ubuntu jammy/universe amd64 python3-grpc-tools amd64 1.14.1-3build1 [1 405 kB]
```
warpinator assembled
`dpkg-buildpackage --no-sign`
Now I'm stuck here
```
warpinator --debug
Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
I hope I have described my path in sufficient detail
