### ISSUE TITLE
No module named 'cryptography'

### ISSUE THREAD

**Issue by coreybruce** [linuxmint/warpinator#128]
Hey I just wanted to report a issue I am having with Warpinator, I am using Arch32 and I have tried both the package on the repo and the warpinator-git package on the AUR and run into the same error message ```No module named 'cryptography'```

**Comment by xenopeek** [comment]
Is the `python-cryptography` package from the Arch32 repository installed?

**Comment by coreybruce** [comment]
Yes and it will still say ```No module named 'cryptography'```

**Comment by xenopeek** [comment]
You'll have to investigate what's wrong with your Python install. I don't know Arch32. You might instead take help with troubleshooting this from their forum. At least get a confirmation from another Arch32 user they can reproduce this issue.

Maybe you installed Python modules outside of pacman, without using virtualenv?

Try a short test from the terminal:

1. Confirm that `which python3` replies `/usr/bin/python3`.
2. Check the version with `python3 --version`. Unless Arch32 is holding back packages it should be 3.10.4.
3. Start the interactive Python console with `python3` and paste these commands in to it and press Enter to run:
```
from cryptography import x509
from cryptography.hazmat.primitives import serialization as crypto_serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend as crypto_default_backend
from cryptography.x509.oid import NameOID
```
That's the bit that is in Warpinator auth.py for importing from the cryptography module. See if this gives any errors in the output. It will output nothing if it went okay and you're back on the >>> prompt. Ctrl+D to leave the Python console.

**Comment by coreybruce** [comment]
my python version is 3.10.4-1.0 

I reinstalled python3 and now when I run Warpinator I get this message suggesting it cant find the lib file it needs

```
libabsl_time_zone.so.2111.0.0: cannot open shared object file: No such file or directory
```

**Comment by coreybruce** [comment]
Waprinator should be looking for the lib files it needs that aren't statically versioned,these are the libs I had to symlink as a work around and the commands I did 

```
sudo ln -s /usr/lib/libabsl_time_zone.so /usr/lib/libabsl_time_zone.so.2111.0.0

sudo ln -s /usr/lib/libabsl_status.so /usr/lib/libabsl_status.so.2111.0.0

sudo ln -s /usr/lib/libabsl_spinlock_wait.so /usr/lib/libabsl_spinlock_wait.so.2111.0.0

sudo ln -s /usr/lib/libabsl_cordz_info.so /usr/lib/libabsl_cordz_info.so.2111.0.0

sudo ln -s /usr/lib/libabsl_cord.so /usr/lib/libabsl_cordz_info.so.2111.0.0

sudo ln -s /usr/lib/libabsl_statusor.so /usr/lib/libabsl_statusor.so.2111.0.0

sudo ln -s /usr/lib/libabsl_cord.so /usr/lib/libabsl_cord.so.2111.0.0

sudo ln -s /usr/lib/libabsl_cord.so /usr/lib/libabsl_cord.so.2111.0.0

sudo ln -s /usr/lib/libabsl_time.so /usr/lib/libabsl_time.so.2111.0.0

sudo ln -s /usr/lib/libabsl_hash.so /usr/lib/libabsl_hash.so.2111.0.0

sudo ln -s /usr/lib/libabsl_str_format_internal.so /usr/lib/libabsl_str_format_internal.so.2111.0.0
```

After doing that I ran into this next issue with python 3.10

```
[corey@Corey-Fujitsu ~]$ warpinator
/usr/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-i386-linux-gnu.so: undefined symbol: _ZN4absl12lts_2021110213time_internal12IDivDurationEbNS0_8DurationES2_PS2_
```

Found a similar issue to do with grpc

https://github.com/grpc/grpc/issues/25235

**Comment by coreybruce** [comment]
Any feedback at all about this?

**Comment by mtwebster** [comment]
Warpinator is a python program that imports python modules. If these modules are broken or missing it's an issue with those packages on your distro or perhaps the system itself.

**Comment by coreybruce** [comment]
> Warpinator is a python program that imports python modules. If these modules are broken or missing it's an issue with those packages on your distro or perhaps the system itself.

But you can clearly see I am having issues with it looking for old dependencies when there is a newer version avaliable

it's using 2111.0.0 when there is a newer version available also it shouldn't be looking for a static version, this has not been resolved so please don't close it.

**Comment by mtwebster** [comment]
Warpinator is not looking for specific versions. It's trying to load a module, and python decides the rest. This is your python setup or some sort of packaging problem. Maybe try this from a new user account? Have you tried to get any support from your distro's forums/support channels?

How did you install all the modules? Using pacman or pip? I don't recommend this at all but you could try installing the pip version of grpcio.

We're not trying to avoid helping. There's nothing we can do except offer suggestions which is what we're doing. You'd be better off asking them some place where people know your distro.

**Comment by coreybruce** [comment]
No not yet, I came to the devs first to report the issue but I will also report it to the Arch32 devs and link this to them to read through

**Comment by andreasbaumann** [comment]
Arch32 dev chiming in here :-)
libabsl_time_zone.so.2111.0.0: cannot open shared object file: No such file or directory

abseil-cpp version mismatch.

I'm pretty sure, this is a pure Arch32 problem. :-)
