### ISSUE TITLE
[FAIL] Kubuntu 21.10

### ISSUE THREAD

**Issue by juanpc2018** [linuxmint/warpinator#132]
$ sudo dpkg -i *warp*.deb
Selecting previously unselected package warpinator.
(Reading database ... 360676 files and directories currently installed.)
Preparing to unpack warpinator_1.2.12_all.deb ...
Unpacking warpinator (1.2.12) ...
dpkg: dependency problems prevent configuration of warpinator:
 warpinator depends on gir1.2-xapp-1.0 (>= 1.6.0); however:
  Package gir1.2-xapp-1.0 is not installed.
 warpinator depends on python3-setproctitle; however:
  Package python3-setproctitle is not installed.
 warpinator depends on python3-xapp (>= 1.6.0); however:
  Package python3-xapp is not installed.
 warpinator depends on python3-netaddr; however:
  Package python3-netaddr is not installed.
 warpinator depends on python3-ifaddr; however:
  Package python3-ifaddr is not installed.

dpkg: error processing package warpinator (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.69ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libglib2.0-0:i386 (2.68.4-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.68.4-1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 warpinator

**Comment by juanpc2018** [comment]
$ sudo dpkg -i *warp*.deb
[sudo] password for mama: 
Selecting previously unselected package warpinator.
(Reading database ... 360988 files and directories currently installed.)
Preparing to unpack warpinator_1.2.12_all.deb ...
Unpacking warpinator (1.2.12) ...
Setting up warpinator (1.2.12) ...
Processing triggers for mailcap (3.69ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libglib2.0-0:i386 (2.68.4-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.68.4-1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

**Comment by juanpc2018** [comment]
Works Ok.

**Comment by mtwebster** [comment]
Good to hear.

fyi, dpkg doesn't handle dependencies, it only complains about them. Many times you can run `apt install -f` after and it will fix things, otherwise you just manually install what's missing.
