### ISSUE TITLE
CPU usage on Linux Mint 21

### ISSUE THREAD

**Issue by reticulatus** [linuxmint/warpinator#137]
After doing fresh installs of LM 21 Mate on my 3 PCs I noticed that the warpinator process (v1.2.13) is running at a higher % cpu than it did on LM 20.3.

PC 1 (12 year old desktop) uses 10 - 11% cpu.
PC 2 (1 year old desktop) uses 8 - 12% cpu.
PC 3 (3 year old laptop) uses 17 - 28% cpu!

The cpu usage was measured while warpinator was _not_ transferring any files. 

I also noticed that the cpu usage tends to increase slowly over time while it is idle. After rebooting PC 2, warpinator was showing 8.6% cpu, but 40 minutes later it was showing 10.3%.

I also tested it running from a live LM 21 Mate ISO and got similar figures to the PC running its installed version.

I posted a message about this on Linux Mint forums:
https://forums.linuxmint.com/viewtopic.php?f=47&t=380052. 

One member running a fresh install of LM 21 Cinnamon was only getting 3.5 to 4%, which is the sort of figure I would have expected.

Another member running  LM 21 Xfce on an HP Elitebook was getting 17.5% to 18%.

Is this a known issue? 

What is warpinator doing that uses this much cpu? 

Is there anything that can be done to reduce cpu usage, apart from closing the application when not required?

**Comment by mtwebster** [comment]
It should be using next to nothing when idle. Two machines I just checked both show ~1-3% at idle. During a transfer it goes up to around 4%.

This is in Cinnamon - I'll try mate and xfce when I get a chance.

If you run it from a terminal using `warpinator --debug` does it show anything?

**Comment by mtwebster** [comment]
I did a quick check on a mate and xfce virtual machine, and it looks like the issue is only apparent in mate - the process never actually 'sleeps'. I'll try to see what's keeping it active.

**Comment by reticulatus** [comment]
I have installed the package on all 3 of my PCs running LM 21 Mate. After letting the new warpinator process settle down I am now getting:
PC1 : 0.5%
PC2 : 1.4%
PC3 : 1.2%

That's a big reduction! I also copied a couple of files with no issues.
