### ISSUE TITLE
Warpinator, built from source, hangs on startup on Ubuntu-22.04.1 LTS

### ISSUE THREAD

**Issue by vobine** [linuxmint/warpinator#138]
Warpinator starts and displays its window, but then hangs and does not respond to any interaction.  Only `kill -9` stopped it.

Happens with both 1.2.3 and 1.2.13.

Strace has **a lot** of lines of the form:
```
1070072 17:36:09.220924 futex(0x55a6727f8eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
1070138 17:36:09.220940 futex(0x55a6727f8eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
1070072 17:36:09.221024 <... futex resumed>) = 0
1070138 17:36:09.221039 <... futex resumed>) = 0
1070072 17:36:09.221049 futex(0x55a6727f8ea8, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=200377, tv_nsec=578519491}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
1070138 17:36:09.221145 futex(0x55a6727f8ea8, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=200377, tv_nsec=578530543}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
1070139 17:36:09.224438 <... futex resumed>) = -1 ETIMEDOUT (Connection timed out)
```

I'm going to try to narrow this down when I get a chance, but I'm hoping this is obvious to somebody.  Help?

**Comment by mtwebster** [comment]
It's a known issue with Jammy's version of grpc: https://github.com/linuxmint/warpinator/issues/127

build with `-Dbundle-grpc-with-py310=true`

You should be able to just use dpkg-buildpackage also - that would have enabled this flag automatically.

Ordinarily I'd suggest installing the pip version as an alternate workaround, but there's another cpu-related issue in gprcio > 1.44 currently (https://github.com/linuxmint/warpinator/issues/137)

**Comment by vobine** [comment]
Thank you, @mtwebster, that worked.
