### ISSUE TITLE
Namespace XApp not available

### ISSUE THREAD

**Issue by tiborh** [linuxmint/warpinator#142]
When trying to execute:
Namespace XApp not available
(it does not start)
(built locally, following instructions in readme.md)

**Comment by leigh123linux** [comment]
Post the output for this

```
python3
import gi
gi.require_version('XApp', '1.0')
from gi.repository import XApp
import xapp
```

**Comment by clefebvre** [comment]
Make sure gir1.2-xapp-1.0 is installed.
