### ISSUE TITLE
Android phone stops being detected after setting secure code

### ISSUE THREAD

**Issue by fabriziojpiva** [linuxmint/warpinator#154]
Hi, the title is quite self-explanatory. I love Warpinator but it is very annoying that when I set the secure code in both phone and laptop with arch linux, the phone stops being detected by the computer. The only workaround that I currently have is to use the default secure code, and before the 60min safety period finishes, I set a different secure code (which does not work, that is why this issue is created) and put back the default secure code to renew the 60min safety window.

Is there a solution to this?

Linux system: Arch linux x64 with kernel 6.1.1-arch1-1
Warpinator 1.4.3

**Comment by mtwebster** [comment]
Does this issue persist if you exit and restart warpinator while using the same code?

**Comment by fabriziojpiva** [comment]
Do you mean the desktop app or the phone?

**Comment by fabriziojpiva** [comment]
Okay I found the solution, after setting the secure code on both phone and computer, you have to force the phone app to be closed completely. Tested and now it works.
