### ISSUE TITLE
Warpinator on two identical Linux Mint Cinnamon 21.1 ain't connecting

### ISSUE THREAD

**Issue by ineuw** [linuxmint/warpinator#155]
I am trying to establish a connection on my Home LAN between two LMC 21.1 desktops. My single router settings identify and display both computer names matching the unique names and IP addresses. Both desktops display each other's name correctly in the Network tab, while at the same time both say that no other computer is found. Both recognize their own shared folders as "Warpinator" and I placed some files in one desktop, and both have "ineuw" as admin.

The attached files:  

[xsession-errors.txt](https://github.com/linuxmint/warpinator/files/10474157/xsession-errors.txt)
[inxi_Fxz.txt](https://github.com/linuxmint/warpinator/files/10474252/inxi_Fxz.txt)

**Comment by mtwebster** [comment]
Have you worked through the troubleshooting steps here?
https://github.com/linuxmint/warpinator#solving-connection-issues

Please attach a debug log for Warpinator (steps at the end of the troubleshooting section), for each machine.

**Comment by ineuw** [comment]
Apologies for the delay. The attached images display my repeatable errors. IP is OK, the SMART/RG cable router shows the connections as well. The LAN IP is also correctly displayed. 

I will post this morning's effort in a few minutes. 


![230123_010200_warpinator_settings_photo_of_laptop_and_desktop_together](https://user-images.githubusercontent.com/10367016/214020678-7d7f43e4-12d7-4a96-98a0-6465ed6af6d8.jpg)

![230123_00-59-57_desktop closeup](https://user-images.githubusercontent.com/10367016/214020680-e5dfe42b-692f-4a04-b37a-9cda3d674de3.jpg)

![230123_005940_laptop_closeup](https://user-images.githubusercontent.com/10367016/214020682-8aececa5-8bf8-4d0f-9008-a7e61c17e5e8.jpg)

**Comment by ineuw** [comment]
Resolved. I had an error in gufw. I disabled it at both end and it works. All this delay was caused by reorganization.

**Comment by ineuw** [comment]
My network experience is limited to Windows home network, and never needed and configured gufw, although it was always installed  along with
