### ISSUE TITLE
Flatpak is version 1.2.14 - latest from Flathub is 1.4.2

### ISSUE THREAD

**Issue by Maltavius** [linuxmint/warpinator#156]
It seemed like I was unable to transfer files to my Steam Deck because the Flatpak version is lagging behind.

Please update the Flatpak version

**Comment by mtwebster** [comment]
There's very little difference between the two versions - the large version bump coincides with a Linux Mint release, which is when we typically update things like translations, but there should be no compatibility issues.

Did you work through the troubleshooting section in the README?
https://github.com/linuxmint/warpinator#troubleshooting-tips

Please provide the logs from a debug session of warpinator (instructions in the README) for both machines if you still have issues.

**Comment by Maltavius** [comment]
I was able to transfer files if I set the Code to Warpinator. I couldn't find anywhere to set another code on the FlatPak version 
Sadly the timelimit cut off my transfer.

**Comment by mtwebster** [comment]
Updated - it usually takes a day for it to be available.

https://github.com/flathub/org.x.Warpinator/commit/522fdc4e94bcc864c5343dc1d6e340c418c73574
