### ISSUE TITLE
Warpinator Flatpak 1.4.4 Doesn't Connect

### ISSUE THREAD

**Issue by JTJersey** [linuxmint/warpinator#157]
Latest update to Warpinator (1.4.4) has cripple all my Mint Linux 21.1 machines.  All of them are on the same code and same ports, but I get nothing except a "no other computers found"  message.  My firewall is OFF.  Does the code have to be in some kind of special format?  Running debug simply says "Failed to load module "xapp-gtk3-module"

**Comment by mtwebster** [comment]
Can you supply a log from this trying to connect:
```
flatpak run org.x.Warpinator --debug
```

The xapp-gtk3-module message can be ignored. The code can be the same as whatever you had before.

**Comment by JTJersey** [comment]
This is what I got this morning when trying debug.  The last lines about the laptop failing verification goes repeats itself dozens of times.  Probably because I haven't yet turned it on in that building this morning.

[Warpinator --debug.log](https://github.com/linuxmint/warpinator/files/10519121/Warpinator.--debug.log)

**Comment by JTJersey** [comment]
The system listed in the debug log as laptop is in a remote area of the building.  I turned it on this morning, but did NOT update to the current 1.4.4 version.  I set it to the same code as the others and all of them are working now.  Is this a matter of if one warpinator equipped computer is not on the same code that none of them work?  I hesitate to update that remote system as the whole thing may fail again like originally and there's no going back if it does.

**Comment by mtwebster** [comment]
I can't reproduce the issue, connecting two machines running the 1.4.4 flatpak version connect fine.

You can reinstall the previous version:
```
sudo flatpak update --commit=42eb0ac6addefda42a1ccfd30ef8cc90e68201c8ab6fbd82ef622da947029d81  org.x.Warpinator
```
Just hit yes at any prompts.

If the code is different on one machine, it prevents any other machines from seeing it, and it from being able to see anything else.  It shouldn't affect other machines from connecting to one another. I'll do a bit more testing to see if that particular scenario causes an issue on my end for some reason.

**Comment by mtwebster** [comment]
You're right I think there is some issue when different codes are being used in the same network.

**Comment by JTJersey** [comment]
Installed the 1.4.4 update on my last system and kept my fingers crossed.  Everything is working as it should.  I'll close this one out and hope that's the end of it.
