### ISSUE TITLE
Warpinator (Flatpak) 1.4.4 still needs UDP port, despite claims in  README.md

### ISSUE THREAD

**Issue by DinoDevel** [linuxmint/warpinator#161]
Hello

There is inconsistencies between statements in README.md and behavior of Warpinator (Flatpak) 1.4.4. While README.md states:
` In current versions of Warpinator (after 1.2.0), only TCP is required, but you should also allow UDP traffic on the transfer port to allow connections with older Warpinator versions.`
In fact two instances of Warpinator (Flatpak) 1.4.4 can't connect with each other while UDP port not opened on firewall. Runnig with --debug option reveals that there is communication problem:
`:warpinator::CRITICAL: Problem while awaiting duplex response - api version 2: StatusCode.DEADLINE_EXCEEDED - Server timed out while waiting for his corresponding remote to connect back to you. -- remote.py (line 257)`
Opening UDP port enables connection but inconsistencies with documentation lead to extra time spent on debugging issue.

**Comment by mtwebster** [comment]
This seems to be specific to flatpak <-> flatpak only. Using a mix of flatpak and normal packaging works fine with the recommended firewall configuration.

I'm not certain why this happens yet, but it seems that opening UDP port 5353 is sufficient to work around this. This is the normal zeroconf/avahi service port, which the firewall typically leaves open anyhow, but for some reason it needs to be explicitly allowed for Warpinator flatpaks to connect reliably.

**Comment by mtwebster** [comment]
Added information to the readme.

b600450a5071978b7d4

**Comment by DinoDevel** [comment]
> This seems to be specific to flatpak <-> flatpak only. Using a mix of flatpak and normal packaging works fine with the recommended firewall configuration.

Sorry, but I didn't mention that port 5353 was opened during troubleshooting and that didn't help.  Also Android version was also having trouble finding flatpak one without UDP por open. The ONLY thing resolved this situation was opening UDP port 42000 on firewalls of flatpak versions. So it seems too soon to close this issue
