### ISSUE TITLE
Please make a release for steam deck because it don't work on silverblue 

### ISSUE THREAD

**Issue by yodatak** [linuxmint/warpinator#185]
### Distribution

steam os

### Package version

latest

### Frequency

Always

### Bug description

we can use warpanitor on all steam deck and silverblue 

### Steps to reproduce

run
https://flathub.org/apps/org.x.Warpinator

i open a pr here
https://github.com/flathub/org.x.Warpinator/pull/14

### Expected behavior

works

**Comment by leigh123linux** [comment]
Duplicate of https://github.com/linuxmint/warpinator/issues/180
