### ISSUE TITLE
Python error when I try to launch Warpinator

### ISSUE THREAD

**Issue by V4lou** [linuxmint/warpinator#194]
### Distribution

Mint 21.2

### Package version

1.6.4

### Frequency

Always

### Bug description

When I launch Warpinator in a terminal, I get this error:

```
Using landlock for incoming file isolation
module 'collections' has no attribute 'MutableMapping'

```

And when I active the debug mode with warpinator --debug I get this errors:

```

2023-10-11 20:17:24,517::warpinator::DEBUG: Migration failed - either migration already happened, or there was nothing to migrate in the first place: g-file-error-quark: No such file or folder (4) -- prefs.py (line 99)
Using landlock for incoming file isolation
module 'collections' has no attribute 'MutableMapping'
```
My version of Python is the 3.11.4

Have you a idea to fix this error ?

Thanks a lot for your responses.

Valentin.

### Steps to reproduce

I have no idea how to reproduce this issue.

Try to run Warpinator with Python 3.11.4 maybe ?

### Expected behavior

Warpinator run without error.

**Comment by mtwebster** [comment]
You need to go back to python 3.10.12 - Everything in your system is expecting that - you'll end up having more problems than just with warpinator. There are often breaking changes between major python versions.

If you need a newer version for specific purposes it's best to do it in some sort of sandbox - *never* replace your system's python.

**Comment by V4lou** [comment]
I have reset the version of python and now I'm on the 3.10.12... but I have the same error...

Can you help me.

Thanks a lot.

Valentin.

**Comment by KevinNadaud** [comment]
Hi,
I get a similar error when I try to launch warpinator:
`nadaud@GEII-2019007501:~$ warpinator
Using landlock for incoming file isolation
Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
`

I  am using Mint 21.2, fresh install. The python version is 3.10.12. From the software manager, I saw protbuf version is 3.12.4-1ubuntu7.22.04.1.
Do you need additionnal informations ?

**Comment by KevinNadaud** [comment]
I check the package installed using pip in the personal folder, protobuf with a version >3.20 (to use tensorflow in my case).
Check in your case if you have package installed with pip (even in your personal folder).

Are they any way to force warpinator to use protobuf version of the distribution instead of personal folder ? (This may be a question more related to python than warpinator).
