### ISSUE TITLE
app doesn't work. Console messeges me- "No module named 'setproctitle'"

### ISSUE THREAD

**Issue by vladimirov-s** [linuxmint/warpinator#199]
### Distribution

ubuntu 22.04

### Package version

1.2.3

### Frequency

Always

### Bug description

Installed, and over( 
Why??

### Steps to reproduce

symple install step by step installation guide. 
Try to start

### Expected behavior

work the app

**Comment by leigh123linux** [comment]
This isn't a bug.
Try installing the dependencies.

 https://github.com/linuxmint/warpinator/blob/master/debian/control#L27
