### ISSUE TITLE
Hardcoded path to bwrap (and python?)

### ISSUE THREAD

**Issue by ProjectMoon** [linuxmint/warpinator#206]
### Distribution

Gentoo Linux

### Package version

1.8

### Frequency

Always

### Bug description

I notice that https://github.com/linuxmint/warpinator/blob/master/src/warpinator-launch.py#L128 has a hardcoded path to `bwrap` at `/bin/bwrap`. On Gentoo, Bubblewrap is available at `/usr/bin/bwrap`. This issue does not affected systemd merged-usr systems, because those have symlinks back to the old `/bin` paths, but on OpenRC systems, merged-usr does not exist. I had to manually symlink `bwrap` and also `python3` to `/bin` to get Warpinator to run (at which point it ran into the endless looping of dconf error, but that's a separate issue).

The ebuild is from [this overlay](https://github.com/SuperTux88/gentoo-overlay/) and the discussion about this started in this issue: https://github.com/SuperTux88/gentoo-overlay/issues/7

The ebuild doesn't do anything to the launcher script (i.e. no patches), and the maintainer's opinion is that this an upstream issue. It's easy enough for me to patch the ebuild or the launch script, but I agree it would be best to address it upstream, if possible.

Is there a reason that `bwrap` and `python3` are hardcoded to `/bin`? Especially because the launch script invokes `/usr/bin/python3`? :thinking: 

### Steps to reproduce

Install from ebuild.

Attempt to run.

### Expected behavior

Warpinator launches in bubblewrap mode.

**Comment by mtwebster** [comment]
No reason, just old age

Thanks
