### ISSUE TITLE
RemoteStatus.UNREACHABLE error

### ISSUE THREAD

**Issue by purpleleaf** [linuxmint/warpinator#28]
two pc o the same net, both running tricia. firewall disabled on both.
one can conect to the other showing remotestatus.Online but file transfer fails, the second report RemoteStatus.UNREACHABLE.

netstat show tcp6 port 42000 listening on all addresses, but nmap doesn't see the port open on both pc, either scanning the other pc pubblic address or ip6-localhost

**Comment by mtwebster** [comment]
Does this still occur on the latest release?
