### ISSUE TITLE
Default location for transferred files looks confusing

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/warpinator#29]
The following seems to be the default location for transferred files.

![image](https://user-images.githubusercontent.com/47056543/80928836-3d8a1f00-8d9f-11ea-8412-7ee4717f4858.png)

What / where is this funny looking folder? I am using a custom icon theme but upon switching back to a default one, I was still puzzled.

EDIT: I found the 'open save folder' - is the 'save folder' the same as the 'location for received files'? - and, judging by that, the funny looking folder icon means to denote my home folder. But my home folder appears already (in two different guises, in fact) within the same menu. Also, the strange icon appears, within that menu, within a section of its own. (I cannot screenshot that, because of X limitations.)

**Comment by mtwebster** [comment]
This is fixed, and besides, a separate folder is created now under home for received files.
