### ISSUE TITLE
Will this support other platforms?

### ISSUE THREAD

**Issue by spsf64** [linuxmint/warpinator#31]
Like Windows, Mac and smartphones (Android and IOS)?
I think if it is not supported it will be a bit useless, because most users don't have 2 linux machines at home...
Thanks for this good program, I am using with Archlinux and Mint on the same network, it works fine!

Ps.
The "nitroshare" project is similar with multi platform, but now I believe it's abandoned, anyway they had good ideas, the link to the project:
https://github.com/nitroshare/nitroshare-desktop

**Comment by ivanaponi** [comment]
Any platform can implement the protobuf messaging protocol and then use Zeroconf, Microsoft Windows may have an issue with Zeroconf and resort to using Bonjour

**Comment by Sraw** [comment]
I agree that this is a little bit useless if it won't support multi-platforms. Or at least support Mac and Windows. I believe many people have the demands to share files between Linux and Windows/Mac.

**Comment by DeadPi** [comment]
It should at least get packages for more distributions like RHEL, Fedora and Arch-like distros

**Comment by mtwebster** [comment]
It's already packaged for arch (aur) but I'm not sure about the others it would be up to some distro maintainers picking it up.

To address the OP question, multi-platform support was planned from the beginning if there was sufficient interest.  It didn't make a whole lot of sense to try and accomplish this right from the start, however. This is after all version 1- we only started on it in February.
