### ISSUE TITLE
1.0.4 start up unsuccessful - TypeError: __init__() got an unexpected keyword argument 'host_ttl'

### ISSUE THREAD

**Issue by SwampRabbit** [linuxmint/warpinator#34]
Hello I am attempting to get a package of 1.0.4 (release) to work, I packaged with pbuilder with no changes to anything, installed build depends and run depends meet requirements or greater.  Nothing special about the physical network.  Warpinator starts up, but I get the following when launching:

```
2020-06-05 09:25:49,163::warpinator: Initializing Warpinator
2020-06-05 09:25:49,228::warpinator: Starting server on 10.10.10.10
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/libexec/warpinator/server.py", line 210, in run
    self.start_zeroconf()
  File "/usr/libexec/warpinator/server.py", line 83, in start_zeroconf
    other_ttl=30)
TypeError: __init__() got an unexpected keyword argument 'host_ttl'
```

I do have system logs, but I didn't see anything in them yet.
Please let me know if there is anything I can provide or do to assist with narrowing down the issue.
Thanks

**Comment by mtwebster** [comment]
Hi, sorry - this is fixed in git master: https://github.com/linuxmint/warpinator/commit/15ce1b783a0e6853492e22cb082eedab799b0cce

There have been quite a few other stability improvements, hopefully we'll get 1.0.5 out there soon.

**Comment by SwampRabbit** [comment]
@mtwebster thank you for the info, I'll package up git master and give it a go.

**Comment by SwampRabbit** [comment]
@mtwebster I've repackaged using Git master and now I get:

`No module named 'netifaces'`

I assume this is python3-netifaces and this is a new build depend / runtime depend not previously listed?  I am packaging for a Debian Buster base BTW.

**Comment by mtwebster** [comment]
Fixed, I had thought it was in the standard python library.

Thanks

**Comment by SwampRabbit** [comment]
@mtwebster You bet, this is turning out to be a really useful application, keep up the great work!
