### ISSUE TITLE
Missing vector icon ?

### ISSUE THREAD

**Issue by Vitexus** [linuxmint/warpinator#39]
Hallo,

Where i can find the icons/hicolor/scalable/apps/warp.svg file ?
Is missing in source code now ? 

I want it for my Debian Buster backport http://repo.vitexsoftware.cz/pool/buster/backports/w/warpinator/

**Comment by mtwebster** [comment]
It got moved to mint-y-icons:

https://github.com/linuxmint/mint-y-icons/blob/master/src/apps/warpinator.svg

**Comment by Vitexus** [comment]
Thank you!
