### ISSUE TITLE
Could anyone help me build an rpm for Fedora?

### ISSUE THREAD

**Issue by heis2201** [linuxmint/warpinator#40]
Could anyone help me build an rpm for Fedora? I could build it locally or use [copr](https://copr.fedorainfracloud.org/).

**Comment by leigh123linux** [comment]
I don't have the time to help or package it for fedora.
Try the link for a start https://leigh123linux.fedorapeople.org/pub/warp/
You will need to compile python3-grpcio and python3-nacl

**Comment by heis2201** [comment]
I'll give it a shot. Thanks for the .spec. and src.rpm files

**Comment by heis2201** [comment]
I tried copr and failed completely. I tried to build rpms locally, I failed. Will seek help in some forums.
