### ISSUE TITLE
cannot import name 'symbol_database'

### ISSUE THREAD

**Issue by nusibrains** [linuxmint/warpinator#41]
Brand new LinuxMint19.3 install, full updated, full dependency installed

dpkg-buildpackage: **ok**
install warpinator_1.0.6_all.deb: **ok**
launch warpinator: **fail**

**error:** cannot import name 'symbol_database'

**result of pip freeze** :

apt-clone==0.2.1
apturl==0.5.2
asn1crypto==0.24.0
beautifulsoup4==4.6.0
Brlapi==0.6.6
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
configobj==5.0.6
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
grpcio==1.19.1
grpcio-tools==1.14.1
Guake==3.0.5
httplib2==0.9.2
idna==2.6
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
meld==3.18.0
nemo-emblems==4.4.0
netifaces==0.10.4
onboard==1.4.1
PAM==0.4.2
pbr==3.1.1
pexpect==4.2.1
Pillow==5.1.0
protobuf==3.6.1
psutil==5.4.2
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
pygobject==3.26.1
PyICU==1.9.8
pyinotify==0.9.6
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparted==3.11.1
pyRFC3339==1.0
python-apt==1.6.5+ubuntu0.3
python-debian==0.1.32
python-xapp==1.8.1
python-xlib==0.20
python3-protobuf==2.5.0
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
scour==0.36
sessioninstaller==0.0.0
setproctitle==1.1.10
six==1.15.0
system-service==0.3
systemd-python==234
tinycss==0.4
ubuntu-drivers-common==0.0.0
ufw==0.36
urllib3==1.22
vboxapi==1.0
xkit==0.0.0
zeroconf==0.19.1

**Comment by mtwebster** [comment]
Did you install dependencies from the ppa from this repository's README?
https://launchpad.net/~clementlefebvre/+archive/ubuntu/grpc?field.series_filter=bionic

Clean out the pip packages (grpcio, grpcio-tools, python3-protobuf, protobuf) and install python3-grpc-tools, python3-protobuf, python3-grpcio from the ppa.

Unfortunately packages involving grpc and protobuf are a bit of a mess at the moment, but I do know that ppa is good for mint 19.3

**Comment by nusibrains** [comment]
that's fine, 
thanks
