### ISSUE TITLE
Connect to Warpinator within a VirtualBox machine

### ISSUE THREAD

**Issue by dazkgoodwin** [linuxmint/warpinator#43]
Hi all, I've seen a Warpinator demo online where the user tests it by connecting Warpinator on the host PC with it running within a VM on another copy of Linux Mint.  I have LM Cinnamon installed on my laptop with LM xfce running with VirtualBox - the VM has no problems connecting to the internet and browsing local Windows Shares.

The 2 Warpinators however, just can't see each other - I'm using the default NAT with Network Adaptor #1 (Intel PRO/1000 MT Desktop).

Any ideas why there's a communication block please?

**Comment by mtwebster** [comment]
You probably need to switch the guest's network type to 'bridged' in the virtual machine settings.  Warpinator can only connect to machines on the same subnet (and by default NAT has the guest on a different one).

**Comment by dazkgoodwin** [comment]
Brilliant, thanks for the tip, it worked! :-)

**Comment by mtwebster** [comment]
Welcome :)
