### ISSUE TITLE
sanning of multiple network interfaces/selection of default interface

### ISSUE THREAD

**Issue by noah1510** [linuxmint/warpinator#44]
At the moment warpinator only scans one network interface (which you cannot select in the settings).
If you have one device which is connected to a wireless interface and both devices are connected to the same wired network.
warpinator cannot establish a connection between them since device 1 only scans the wireless network for devices and device 2 only scans the wired network for devices.
While device 2 detects device 1 it cannot establish a two-way-connection.

It would be nice if you could select the default interface that will be scanned or if warpinator could simply scan all interfaces for devices.

**Comment by mtwebster** [comment]
Selecting a specific interface is definitely in the works.  I'm not sure about *connecting* with multiple interfaces, however, but we will see.

**Comment by mtwebster** [comment]
Interface selection implemented as part of b9f17af46e52576d5fc0c084e6d7e6db67245f42.

Zeroconf seems unreliable regarding multiple interfaces - I can configure it to only listen on a single one, but it still finds hosts from others, and I end up having to filter remote out based on ip address (which isn't perfect).

If you want to experiment with removing this filter, you can remove the `return` here in /usr/libexec/warpinator/server.py:
https://github.com/linuxmint/warpinator/blob/1.1.2/src/server.py#L140-L143 (current release only). If this is something that may be useful to disable, I can see about making it a setting in the next dev cycle. I probably won't be revisiting this before then.

**Comment by ioogithub** [comment]
Is it possible to select the IP yet in version ? Warpinator is definitely grabbing the wrong IP address on the PC.

Version: Stable 5/2/21?

**Comment by mtwebster** [comment]
Assuming you're using the flatpak, I haven't updated the flatpak version yet to include the recent changes. I will in the next week or so probably.

**Comment by ioogithub** [comment]
I tried to use the: add-apt-repository ppa:clementlefebvre/grpc but I got this error:

Err:15 http://ppa.launchpad.net/clementlefebvre/grpc/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done

**Comment by mtwebster** [comment]
what distro are you on?

**Comment by ioogithub** [comment]
I am using KDE Neon 5.22 which I believe is Ubuntu focal. Should this ppa work in my case or is it only specific to Mint? I saw an article that suggested it should work with any Ubuntu 19+

**Comment by mtwebster** [comment]
No don't use the ppa, check out the readme: https://github.com/linuxmint/warpinator#ubuntu-2004-related. That should work fine.
