### ISSUE TITLE
feature? clipboard send

### ISSUE THREAD

**Issue by wolfbiteaus** [linuxmint/warpinator#46]
I still use dukto to send files & folders BUT I find it handy to copy text & send via dukto.

Dukto is pretty dated now but still works (linux,windows,android)
Any chance for a clipboard send with a copy text received?

**Comment by parnikkapore** [comment]
There's also KDE Connect, which offers clipboard sync among other things, and works on other DEs too.

**Comment by vgstef** [comment]
Yeah! I often want to transfer just a few words for one computer to the other (ex. URL, email address, etc.) 

Warpinator could simply have a text field to write or paste some text. Then transfer it to the other computer..

**Comment by mtwebster** [comment]
closing duplicate (https://github.com/linuxmint/warpinator/issues/105)
