### ISSUE TITLE
More detailed build instructions than "Use dpkg-buildpackage..."

### ISSUE THREAD

**Issue by pragma2k** [linuxmint/warpinator#47]
I'm on Ubuntu 20.04 and there is no DEB package or Flatpak (or Snap, but I prefer not to use those), so I need to build my own binaries, but the instructions for doing so are very terse: "Use dpkg-buildpackage, the python3-grpc-tools and python3-grpcio versions in those repos are fine" -- that's it.

I checked and I do have `dpkg-buildpackage` on my machine, but I don't know what the next step is or which ones "those repos" are. It would be helpful if there were a little more detail in the instructions, or at least a pointer to more documentation elsewhere. Improving the README might help someone like the person who opened issue #40, too.

Thank you

**Comment by mtwebster** [comment]
README updated.
