### ISSUE TITLE
Tray icon "invisible" w/o network connection

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/warpinator#49]
Warpinator 1.0.6
LM 20 Cinnamon

Icon is visible when starting Warpinator. When turning off network (e.g. WLAN off), the icon vanishes from the panel.
It looks like invisible, because the icon space is still occupied.
When network connection is established again, the icon is displayed like before.

**Comment by mtwebster** [comment]
Addressed by https://github.com/linuxmint/warpinator/commit/89668b2294b82e449887765f482f6963d75fd365
