### ISSUE TITLE
Build failing on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by TheRealDannyBoy** [linuxmint/warpinator#51]
I've been attempting to build an openSUSE package for Warpinator.  However, both `rpmbuild` and manual builds fail during the compile stage.  The exact output of `ninja -vC builddir` is shown below:

```
ninja: Entering directory `builddir'
[1/1] /usr/bin/meson --internal msgfmthelper ../data/org.x.warpinator.policy.in.in data/org.x.warpinator.policy xml /home/daniel/documents/src/warpinator/po
FAILED: data/org.x.warpinator.policy 
/usr/bin/meson --internal msgfmthelper ../data/org.x.warpinator.policy.in.in data/org.x.warpinator.policy xml /home/daniel/documents/src/warpinator/po
msgfmt: cannot locate ITS rules for ../data/org.x.warpinator.policy.in.in
ninja: build stopped: subcommand failed.
```

I have been unsuccessful in searching for what exactly an ITS rule is.  Any help resolving this issue would be greatly appreciated.  Thanks in advance!

**Comment by mtwebster** [comment]
I think maybe there's a missing dependency. ITS rules tell the build system what parts of a file should be considered considered for translation.  In debian-based systems these are provided by policykit-1 for this particular file.

I have it as a dependency on our debian packaging, but it's not in meson's dependencies (I don't think it has a pkg-config file).

**Comment by TheRealDannyBoy** [comment]
That was it, thanks.  I had to install `polkit-devel`.

**Comment by kukku14** [comment]
> That was it, thanks. I had to install `polkit-devel`.
> 
> **EDIT:** there are some other errors; I'll leave this open for now.
thanks for this.it builds now but i dont know which packages are equivalent in suse fotr these gir1.2-glib-2.0
gir1.2-gtk-3.0 (>= 3.20.0)
gir1.2-xapp-1.0 (>= 1.6.0)

**Comment by mtwebster** [comment]
Can this be closed?

**Comment by rlafuente** [comment]
Had the same error on Debian, the missing package was `libpolkit-gobject-1-dev`
