### ISSUE TITLE
Received file location invalid for folders above home directory

### ISSUE THREAD

**Issue by Grumium** [linuxmint/warpinator#52]
### Platform
Linux Mint 20 Ulyana 
Warpinator 1.0.6+ulyana

### Issue
Locations for received files above the user's home directory `~` are not recognized upon system startup.
Warpinator set to start automatically shows `"invalid save location"`.

However, locations outside of `~` can be selected manually after startup and are valid throughout the active session.

**Comment by mtwebster** [comment]
Can you be a bit more detailed?  Do you mean system locations (outside of /home/<user>) are invalid?

Is this location writable at startup?

**Comment by Grumium** [comment]
Sure. If I set the `Location for received files` to any directory residing at or below `/home/*user*/` these locations are valid even after system reboot. In contrary, whenever I choose a directory like `/mnt/something` or `/media/something_else` Warpinator throws the error `"invalid save location"` after reboot, indicating that it is either missing permissions or cannot find the corresponding directory. However, I can manually select the directory again choosing `"Other..." -> "+ Other Locations"`, which works until I reboot.

**Comment by Grumium** [comment]
Okay, `chmod a+rwx` solved it. Sorry! 
I am wondering why Warpinator does not complain about missing permissions when I first set it manually? Warpinator does not run as root.

**Comment by mtwebster** [comment]
That is weird - do you remember its permissions before you changed it?  It'd be better if it worked with normal permissions - a+rwx scares me :)

**Comment by Grumium** [comment]
Yes, `0755` `rwx-rx-rx` is not working, `0777` `rwx-rwx-rwx` works, even without `a`. I can also take ownership of the directory as the local user to solve the issue.

**Comment by mtwebster** [comment]
Oh then all of this makes sense, if you didn't own the folder.  I would personally go with owning the folder and back to 755 before opening it for anyone, though in practice this probably won't matter for you.

Regardless I think this can be closed.  I may reword the error page to mention permissions/ownership more explicitly.
