### ISSUE TITLE
Manjaro don't show the other Warpinator in the network

### ISSUE THREAD

**Issue by W4WAN-YT** [linuxmint/warpinator#57]
In Manjaro XFCE, I installed Warpinator. I started it in my other PC, a Linux Mint 20 Cinnamon, and then I started it on the Manjaro. 

When searching others users on Manjaro, it shows in terminal :

`warpinator: >>> Discovery: Unable to authenticate with minterwan (192.168.0.14:42000)`
(minterwan is my Mint PC)

I don't know how to repair it

**Comment by mtwebster** [comment]
Closing due to no response, hopefully you got this working. I can re-open if not.
