### ISSUE TITLE
Request: Android file sharing

### ISSUE THREAD

**Issue by mubashir-rehman** [linuxmint/warpinator#61]
About:
Add feature to share files with Android devices.

Explanation:
Just like file sharing between desktops, sometimes we need to share files between desktops and Android devices on common network like WiFi.

Other similar options:
1)Kde Connect (provides sharing files between Android devices and desktops) but I can't find if it is useable for desktop to desktop transfer.
2)Snapdrop (https://github.com/RobinLinus/snapdrop) Might be slow because it requires WebRTC however support many devices
3)Tebleshot(https://GitHub.com/trebleshot) Currently, works good for transfer between Android devices while transfer to and from desktop via browser.

Side suggestion: It might be great to have look at https://github.com/uprotocol for what might be a better solution.

**Comment by Jean28518** [comment]
Or a (direct) connection with kde-connect on android would be great..
So you don't have to install an additional app beside kdeconnect at the smartphone..

**Comment by plain-txt** [comment]
I've found an unofficial Warpinator port for Android (https://github.com/slowscript/warpinator-android) thanks to another open issue. I haven't tested it, but I think this could be a solution.
