### ISSUE TITLE
Warpinator transfer speed painfully slow

### ISSUE THREAD

**Issue by shag00** [linuxmint/warpinator#68]
Started the transfer of my first folder, 100.5GB, and was disappointed to find it will take approx 3.5 hours at around 8 MB/s, significantly slower than a transfer using SMB.

On internet speed test both machines clock around 90 MB/s for both uploads and downloads and SMB speeds are regularly around 60 MB/s.

**Comment by mtwebster** [comment]
This isn't really something we can do anything about.

For my test case:
- Warpinator: 11 MB/s transfer speed:
- iperf client/server test: 94.2 Mbits/sec, which is about 11.7 MB/s
- ftp using filezilla --> vsftpd:  11 MB/s

If anything is limiting things it's probably something on your network. I get 250 MB/s+ transferring to a hosted virtual machine - the program itself isn't slowing things down.

Compression is now available, and can help, but only on files that aren't already compressed/optimized.
