### ISSUE TITLE
can't install from POP repository

### ISSUE THREAD

**Issue by steveR-GH** [linuxmint/warpinator#72]
tried to install warpinator from the POP_76 repository and this message:
![Screenshot from 2021-03-01 12-47-48](https://user-images.githubusercontent.com/79874791/109559150-8d0caa80-7a97-11eb-93b2-d5bdb6dbbd3d.png)

![Screenshot from 2021-03-01 12-49-15](https://user-images.githubusercontent.com/79874791/109559208-9f86e400-7a97-11eb-86cf-89f82e6337e6.png)

**Comment by steveR-GH** [comment]
Wow thanks for the fast response. By POP I meant system 76 Pop O.S. their
repository uses flathub and that's supposedly where I'm trying to download
Warpinator. I keep getting the same message.

**Comment by mtwebster** [comment]
Weird - I'm not having any issue - do you have a .flatpakrepo file for their repository? Or are they just redirecting from flathub?

That's not a very useful error message :)

Maybe wait a few hours and give it another try.

**Comment by steveR-GH** [comment]
sorry I"m a NOOB don't know what .flatpakrepo file is but I  have left System76  with a help ticket. they probably will respond within 24 hours.  My guess is they will just tell me to contact Github. So I just went ahead and tried.  I believe flatpack is just a secondary part of their repository.  They have forked their own O.S. based on UBUNTO  20.4. It comes installed on their custom built computers. It's called Pop_os. They have their own repository that also offers some flatpack.  Thanks so much for your response. It's things like this that are helping me to learn.  Much appreciated.

**Comment by steveR-GH** [comment]
this is the error I get when I try installing via terminal:

![Screenshot from 2021-03-01 17-41-07](https://user-images.githubusercontent.com/79874791/109689319-6b1c3200-7b42-11eb-8215-830feb933dee.png)

**Comment by mtwebster** [comment]
Can this be closed? This doesn't appear to be a warpinator issue.

**Comment by steveR-GH** [comment]
Oh yes. And Warpinator is now downloadable on your site. Thanks for your
help!
