### ISSUE TITLE
Interface selection

### ISSUE THREAD

**Issue by macbeto** [linuxmint/warpinator#74]
I don't see how I can select the network interface.
I've two computers, one with network wired and wireless (being tethering server) and another just with wifi connected to the previous. 
The first one only shows the ip address of the wired ethernet inteface, and the second one the ip address of the wireless, so they never see each other.
I don't know if there is a way to switch the network interface in the first computer to be in the same network segment of the second, but I don't see that option, so I can't use warpinator right now.
Regards

**Comment by macbeto** [comment]
Ok, I see now there is a Pull Request with this petition.

**Comment by mtwebster** [comment]
Implemented as part of b9f17af46e52576d5fc0c084e6d7e6db67245f42
