### ISSUE TITLE
Can't run it on Fedora 34 Beta

### ISSUE THREAD

**Issue by pedrofleck** [linuxmint/warpinator#76]
When I try to run the flatpak version of Warpinator (1.1.1) on Fedora 34 Beta (Gnome 40), I get the following error and the application won't run:
`(warpinator:2): Gtk-ERROR **: 17:16:52.095: failed to add UI: /app/share/warpinator/main-window.ui:23:1 Invalid object type 'XAppGtkWindow'`

**Comment by mtwebster** [comment]
Hi, is this the package off of flathub?  I can't reproduce this - libxapp is bundled with the warpinator flatpak so I'm not sure how it could occur.

**Comment by leigh123linux** [comment]
It works ok on my F34 Cinnamon installation.

**Comment by pedrofleck** [comment]
> Hi, is this the package off of flathub? I can't reproduce this - libxapp is bundled with the warpinator flatpak so I'm not sure how it could occur.

Yes, the one from flathub, it used to work on Fedora 33 (and it still does on my desktop with it). 

> It works ok on my F34 Cinnamon installation.

Maybe it has something to do with Gnome 40?

**Comment by mtwebster** [comment]
It shouldn't - that's the whole point of flatpaks, they're unaffected by the distro they're on.

Do you have warpinator also installed via normal means? (I'm not sure if anyone packages it or not on fedora) - or did you attempt to build it?  Running `flatpak run org.x.Warpinator` has the same results?

**Comment by pedrofleck** [comment]
@mtwebster 
Yeah, my thought also, but I don't know what's happening.
No, I'm not sure if someone packaged a rpm for it, I googled it and couldn't find one either. The error message was shown when running `flatpak run org.x.Warpinator`.

**Comment by ruffson** [comment]
I don't think this is a F34 problem. I have the same problem on F33. But not right after starting the program.
 
Here is what I did: Start it, enable tray icon, close the main window and leave it in the background, get the main window back via the tray icon, disable the try icon, close the main window.
Now since then I cannot get it to start up again. See error below.

```
flatpak run org.x.Warpinator
Gtk-Message: 17:18:51.124: Failed to load module "pk-gtk-module"
2021-04-02 17:18:51,266::warpinator: Initializing Warpinator

(warpinator:2): Gtk-ERROR **: 17:18:51.270: failed to add UI: /app/share/warpinator/main-window.ui:23:1 Invalid object type 'XAppGtkWindow'

```

**Comment by mtwebster** [comment]
Thanks, now I can reproduce.

**Comment by mtwebster** [comment]
You can work around this temporarily by running:
```
flatpak run --command=gsettings org.x.Warpinator set org.x.warpinator.preferences use-tray-icon true
```

This will re-enable the tray icon (which in doing, will prevent the crash).

**Comment by mtwebster** [comment]
This should take care of it:
https://github.com/flathub/org.x.Warpinator/commit/cbf047d7f4954fa9f878924b7d3f1d6362c2a9c7

I'm not sure how long it'll take for that to become available on flathub.

**Comment by pedrofleck** [comment]
@mtwebster The workaround did work! I just need to remember to close it in the menu and not the "X' button because I don't use tray icons.
