### ISSUE TITLE
Bug report: Failed to start GRPC server

### ISSUE THREAD

**Issue by parijat-technicise** [linuxmint/warpinator#84]
- I am trying to connect my android phone with my desktop wired connected by a router. When I start the app then this toast message comes & can't connect to desktop, but it works fine with my laptop which is connected to the same local network.

### Screenshot from desktop & phone

![image](https://user-images.githubusercontent.com/58384482/119199167-3a47fb00-baa8-11eb-986e-0ca8bd7aa4d6.png)

![Screenshot_2021-05-22-02-21-47-90_e5dfa06d167cd17bc8cd18a8d0448e8a](https://user-images.githubusercontent.com/58384482/119198832-a2e2a800-baa7-11eb-9c6d-98e094597d78.jpg)

**Comment by slowscript** [comment]
This is most likely an issue with the Android version. Please move the bug report there: https://github.com/slowscript/warpinator-android/issues. When you do, please include a debug log - enable the appropriate setting, restart the app an then you will find it under Android/data/slowscript.warpinator/files
