### ISSUE TITLE
Warpinator 1.2.0 can't run

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/warpinator#88]
Warpinator version: 1.2.0+uma
Error output: cannot import name 'ServiceInfo' from 'zeroconf_' (/usr/libexec/warpinator/zeroconf_/__init__.py)

Hi,

I think there is a missing dependency.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/warpinator/commit/064f7d830545b8751a6bfb3df79cc18a262c353f

Thanks

If you don't want to wait for the new version, you can download the missing file yourself:
```
curl -Ss https://raw.githubusercontent.com/jstasiak/python-zeroconf/0.29.0/zeroconf/__init__.py | sudo tee  /usr/libexec/warpinator/zeroconf_/__init__.py
```

**Comment by kelebek333** [comment]
@mtwebster , Thank you.

I can build package with bundle-zeroconf on local. But, the package can't build on launchpad. https://launchpadlibrarian.net/542503978/buildlog_ubuntu-focal-amd64.warpinator_1.2.0-1+klbkfocal_BUILDING.txt.gz

Upon this, I added python3-zeroconf 0.30.0 to the PPA repository, Warpinator 1.2.0 package was able to created with bundle-zeroconf=false. https://launchpad.net/~kelebek333/+archive/ubuntu/mint-tools

Now, I can use Warpinator without any issue. 

Thank you very much for your interest and efforts. 

Best regards.
