### ISSUE TITLE
Without support for other OSs, this has limited utility.

### ISSUE THREAD

**Issue by rwperrott** [linuxmint/warpinator#96]
I will ignore this until it has multi-OS support, possibly via `python` implementation; it's useless to me without support for Windows 10. This could also make then port on Android more useful too.

`LANShare` was far more interesting for ad hoc file transfers, because it supported multiple OSs, however it developed annoying network target discovery issues on Mint, but not Windows, and I couldn't limit its excessive parallel use of files and connections, so I lost interest.

How about Linux Mint lobby the Linux mount author(s) for actually useful mount failure logging and providing a GUI to guide creation, editing and testing `fstab` persistent SMB mount lines, with the same for setting up SMB server configuration and persistent SMB shares too? NFS and WebDAV are often not practical alternatives. It may be useful to allow issuing and support for a transient login for an SMB share, possibly a transient one, to allow ad hoc file transfers. This one of many reasons it is impractical for me to migrate my remaining Windows machines to a free OS like Linux or FreeBSD.

**Comment by leigh123linux** [comment]
Android is already supported

https://play.google.com/store/apps/details?id=slowscript.warpinator&hl=en_GB&gl=US

warpinator is python3 code and could be ported by an interested party.
