### ISSUE TITLE
Issue with the automatic firewall settings

### ISSUE THREAD

**Issue by NicoBXL** [linuxmint/warpinator#98]
I don't know if I'm the only one who had the issue, but for me the automatically generated firewall rules didn't work to connect my laptop (on Cinnamon) with my Android phone.
I think the rules didn't include UDP. Manually setting them for both TCP and UDP resolved my connexion problem.

**Comment by mtwebster** [comment]
Thanks - there's been an issue connecting between different versioned clients, I should have left udp in there, as the older versions use it still.

**Comment by NicoBXL** [comment]
Glad to help, seems like this is my first useful contribution on github :D
